#!/usr/bin/env python3
"""
reverse_shellcode.py - recover the original shellcode from a Killer payload.

Stored blob layout:  reverse( AES256_CBC(key, iv, PKCS7(original)) )
This tool:           reverse(stored) -> AES-CBC decrypt -> PKCS7 unpad -> original

Sources:
    --header payload.h   parse aesKeyEnc / aesIvEnc / shellcode from the C header
    --blob file.bin      raw stored blob (requires --key/--iv)
    --hex "0x..,0x.."    inline stored blob bytes (requires --key/--iv)
    --reverse-only       only reverse the input bytes (no AES, no unpad)

Output: -o out.bin (default shellcode_recovered.bin); print hex with --hex-out.

Usage:
    python3 reverse_shellcode.py --header payload.h -o original.bin
    python3 reverse_shellcode.py --blob blob.bin --key <64 hex> --iv <32 hex>
    python3 reverse_shellcode.py --reverse-only --blob blob.bin -o reversed.bin
"""
import argparse
import re

from Crypto.Cipher import AES

KEY_XOR = 0xB6
BLOCK = 16


def pkcs7_unpad(data: bytes) -> bytes:
    if len(data) == 0 or len(data) % BLOCK != 0:
        raise ValueError("ciphertext length must be a non-zero multiple of 16")
    pad = data[-1]
    if pad < 1 or pad > BLOCK or data[-pad:] != bytes([pad]) * pad:
        raise ValueError("invalid PKCS7 padding (wrong key/iv, truncated blob, or --reverse-only output)")
    return data[:-pad]


def parse_header(path: str):
    text = open(path, "r", errors="replace").read()

    def grab(name: str) -> bytes:
        m = re.search(r"%s\s*\[\s*\]\s*=\s*\{(.*?)\};" % name, text, re.S)
        if not m:
            raise SystemExit(f"error: {name}[] not found in {path}")
        nums = [int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{1,2})", m.group(1))]
        return bytes(nums)

    key_enc = grab("aesKeyEnc")
    iv_enc = grab("aesIvEnc")
    blob = grab("shellcode")

    if len(key_enc) < 32 or len(iv_enc) < 16:
        raise SystemExit("error: key/iv arrays too short in header")
    key = bytes(b ^ KEY_XOR for b in key_enc[:32])
    iv = bytes(b ^ KEY_XOR for b in iv_enc[:16])
    if key_enc[32] != 0x00:
        print("[!] warning: aesKeyEnc has no 0x00 terminator at index 32")
    if iv_enc[16] != 0x00:
        print("[!] warning: aesIvEnc has no 0x00 terminator at index 16")
    return key, iv, blob


def load_blob(args) -> bytes:
    if args.header:
        key, iv, blob = parse_header(args.header)
        return key, iv, blob
    if args.blob:
        blob = open(args.blob, "rb").read()
    elif args.hex:
        nums = [int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{1,2})|[0-9a-fA-F]{2}", args.hex)]
        blob = bytes(nums)
    else:
        raise SystemExit("error: need --header, --blob or --hex")
    if args.reverse_only:
        return b"", b"", blob
    if not args.key or not args.iv:
        raise SystemExit("error: --key and --iv (hex) required with --blob/--hex (unless --reverse-only)")
    key = bytes.fromhex(args.key)
    iv = bytes.fromhex(args.iv)
    if len(key) != 32 or len(iv) != 16:
        raise SystemExit("error: key must be 64 hex chars, iv 32 hex chars")
    return key, iv, blob


def main() -> None:
    ap = argparse.ArgumentParser(description="reverse the Killer AES-256-CBC stored shellcode blob")
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--header", help="payload.h generated by encryptor.py")
    src.add_argument("--blob", help="raw stored blob file")
    src.add_argument("--hex", help="stored blob as inline hex")
    ap.add_argument("--key", help="AES key as 64 hex chars (only with --blob/--hex)")
    ap.add_argument("--iv", help="IV as 32 hex chars (only with --blob/--hex)")
    ap.add_argument("--reverse-only", action="store_true", help="just reverse the input bytes, no AES/unpad")
    ap.add_argument("-o", "--output", default="shellcode_recovered.bin")
    ap.add_argument("--hex-out", action="store_true", help="print result as hex instead of writing a file")
    args = ap.parse_args()

    key, iv, blob = load_blob(args)

    if args.reverse_only:
        result = blob[::-1]
        print(f"[*] reversed {len(blob)} bytes (no AES applied)")
    else:
        if len(blob) % BLOCK != 0:
            raise SystemExit(f"error: blob size {len(blob)} is not a multiple of 16 (truncated?)")
        ct = blob[::-1]
        plain_padded = AES.new(key, AES.MODE_CBC, iv).decrypt(ct)
        result = pkcs7_unpad(plain_padded)
        print(f"[+] decrypted {len(ct)} bytes, unpadded to {len(result)} bytes")

    if args.hex_out:
        print(result.hex())
    else:
        with open(args.output, "wb") as f:
            f.write(result)
        print(f"[+] wrote {args.output} ({len(result)} bytes)")


if __name__ == "__main__":
    main()
